### ISSUE TITLE
Badges respond weirdly when user description is updated in user profile

### ISSUE THREAD

**Issue by GordiArtur** [BadgeBook/LinkedOut#19]

**Comment by GordiArtur** [comment]
Also potentially breaks server.js 
```
throw err; // Rethrow non-MySQL errors
^

TypeError: Cannot read property 'changedRows' of undefined
at Query.<anonymous> (/app/database.js:119:23)
at Query.<anonymous> (/app/node_modules/mysql/lib/Connection.js:502:10)
at Query._callback (/app/node_modules/mysql/lib/Connection.js:468:16)
at Query.Sequence.end (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
at Query.ErrorPacket (/app/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
at Protocol._parsePacket (/app/node_modules/mysql/lib/protocol/Protocol.js:278:23)
at Parser.write (/app/node_modules/mysql/lib/protocol/Parser.js:76:12)
at Protocol.write (/app/node_modules/mysql/lib/protocol/Protocol.js:38:16)
at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:91:28)
at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:502:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! LinkedOut@1.0.0 start: 'node server.js'
npm ERR! Exit status 1
```

**Comment by GordiArtur** [comment]
#30  Merged to develop
